package com.transformacion.fitness.domain.model

/**
 * Categorías de exercicios para clasificar o tipo de movemento.
 */
enum class ExerciseCategory {
    EMPUXE,      // Flexións, fondos...
    TRACCION,    // Remos, dominadas...
    PERNAS,      // Sentadillas, zancadas...
    CORE         // Planchas, abdominais...
}
